// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qbfgscsbxdkewympffxo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFiZmdzY3NieGRrZXd5bXBmZnhvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU4MzY1MjQsImV4cCI6MjA2MTQxMjUyNH0.Ip0fxsoWtAknnfJqRdz5j2fa4cccLk7S1Y7Cz206Ea0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);